apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails
        image: rithwik504/rails-app:latest
        ports:
        - containerPort: 3000
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "bundle exec rails db:migrate RAILS_ENV=development"]
        env:
          - name: DATABASE_URL
            value: postgres://postgres:password@postgres:5432/Budgy_development
          - name: DATABASE_HOST
            value: postgres
          - name: DATABASE_USERNAME
            value: postgres
          - name: DATABASE_PASSWORD
            value: password
          - name: RAILS_ENV
            value: development
 
---
apiVersion: v1
kind: Service
metadata:
  name: rails-app
spec:
  type: NodePort
  selector:
    app: rails-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000  


