apiVersion: v1
kind: Pod
metadata: 
  name: pods
spec:
  containers:
    - name: test
      image: alpine
      args:
        - sleep
        - 1d
      env: 
        - name: USERNAME
          value: admin
        - name: PASSWARD
          value: admin@123     