---
aipVersion: v1
kind: Pod
metadata:
  name: activity-2
spec:
  containers:
    - name: web-1
      image: nginx1.27
    - name: web-2
      image: busybox1.37

---
apiVersion: v1
kind: Pod
metadata:
  name: activity-3
spec:
  containers:
    - name: web
      image: nginx:1.27
    - name: sidecar
      image: alpine
      args: # cmd
        - sleep
        - 1d