---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: books-svc
  labels:
    app: book-svc
  annotations:
    kubernetes.io/change-cause: "version v1.0"      
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: book-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: book-svc
    spec:
      containers:
        - name: books-svc
          image: shaikkhajaibrahim/libbookssvc:1.0
          ports:
            - containerPort: 8000
              name: books-svc
              protocol: TCP
          envFrom:
            - secretRef:
                name: books-svc-secrets
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 8000
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /docs
              port: 8000
          startupProbe:
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            exec:
              command:
                - /bin/sh
                - -c
                - ps aux | grep uvicorn  
          resources: 
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: book-svc  
  name: books-svc 
spec:                       
  selector:
    app: book-svc
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP  