---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib-webstore
  labels:
    app: webstore
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: webstore
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: webstore
      name: lib-webstore  
    spec:
      containers:
        - name: lib-webstore
          image: shaikkhajaibrahim/libwebstore:1.0
          envFrom:
            - configMapRef:
                name: library-config
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
          startupProbe:
            initialDelaySeconds: 10 
            failureThreshold: 3
            periodSeconds: 5
            successThreshold: 1
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: 
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: librarystore-svc
spec:
  type: NodePort
  selector:
    app: webstore
  ports:
  - port: 80
    targetPort: 3000               
