---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: users-db
  labels:
    app: user-db
  annotations:
    kubernetes.io/change-cause: "version v1.0"      
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: users-db
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              name: users-db
              protocol: TCP
          envFrom:
            - secretRef:
                name: users-db-secrets   
          resources: 
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-db  
  name: users-db  
spec:                       
  selector:
    app: user-db
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP  