---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-store
  labels:
    app: web
  annotations:
    kubernetes.io/change-cause: "version v1.0"  
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: web-store
      labels:
        app: web
      annotations:
        app.kubernetes.io/created-by: "controller-manager"
    spec:
      containers:
        - name: web-store
          image: shaikkhajaibrahim/dmtest:1.0
          resources:
            requests:
              memory: 24M
              cpu: 50m
            limits:
              memory: 100M
              cpu: 200m
          ports:
            - containerPort: 80
              protocol: TCP 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: app-svc
spec: 
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web-svc


