---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: books-svc-rs
  name: books-svc  
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: books-svc
  template:
    metadata:
      labels: 
        app: books-svc
      name: books-svc
    spec:
      containers: 
        - name: books-svc
          image: shaikkhajaibrahim/libbookssvc:1.0
          env: 
            - name: DATABASE_URL
              value: "postgresql://user:password@books-db:5432/booksdb"    
            - name: SECRET_KEY
              value: 'YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k'  
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m
          ports: 
            - containerPort: 8000
              protocol: TCP      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: books-svc
  name: books-svc    
spec:
  selector:
    app: books-svc
  type: ClusterIP
  ports: 
    - port: 8000
      targetPort: 8000  
