---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: webstore
  name: lib-webstore-rs
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: webstore
  template:
    metadata:
      labels:
        app: webstore
      name: lib-webstore-rs
    spec:
      containers:
        - name: lib-webstore
          image: shaikkhajaibrahim/libwebstore:1.0
          env:
            - name: REACT_APP_BACKEND_API_URL
              value: http://users-svc:8000/api/v1
            - name: REACT_APP_BOOKS_API_URL
              value: http://books-svc:8000/api/v1/books
            - name: REACT_APP_USERS_API_URL
              value: http://users-svc:8000/api/v1/users    
          resources: 
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m  
          ports:  
            - containerPort: 3000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: librarystore-svc
spec:
  type: LoadBalancer
  selector:
    app: webstore
  ports:
  - port: 80
    targetPort: 3000             