---
apiVersion: v1
kind: Pod
metadata:
  name: mangodb
  labels: 
    name: mangodb
spec:
  containers:
    - name: mangodb
      image: mongo:6-jammy
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "1000Mi"
          cpu: "1500m"
      ports:
        - containerPort: 27017
      envFrom:
        - configMapRef:
            name: mangodb-pod
      volumeMounts:
        - name: libdb
          mountPath: /data/db  /data/configdb    
  volumes:
    - name: libdb
      persistentVolumeClaim:
        claimName: mangodb          
